languages = {

    {
        name = 'ENGLISH',
        newGame = 'NEW GAME',
        highScores = 'HIGH SCORES',
        options = 'OPTIONS',
        exit = 'EXIT',
        score = 'SCORE',
        lives = 'LIVES',
        paused = 'PAUSED',
        resume = 'RESUME',
        abort = 'ABORT MISSION',
        gameOver = 'GAME OVER',
        gameOverComment1 = 'WOAH! NEW HIGH SCORE!',
        gameOverComment2 = "YAY! YOU'RE IN TOP 5!",
        gameOverComment3 = 'OOF! THOSE CATS ARE TOUGH!',
        scoreIs = 'YOUR SCORE IS ',
        playAgain = 'PLAY AGAIN',
        menu = 'MENU',
        back = 'BACK',
        language = 'LANGUAGE',
        sound = {
            [1] = 'SOUND IS ON',
            [0] = 'SOUND IS OFF'
        },
        choosePlayer = 'CHOOSE YOUR FIGHTER',
        choosePlayerTitle = 'YOUR FIGHTER',
        chooseBullet = 'CHOOSE YOUR WEAPON',
        chooseBulletTitle = 'YOUR WEAPON',
        select = 'SELECT',
        playersNames = {'OUR HERO', 'SUIT', 'TANK TOP GUY', 'PRETTY IN PINK', 'THE MAILMAN', 'RAPPER',
        'TUBA PLAYER', 'FIERCE NINJA', 'GREEN RANGER', 'PINK HORSE', 'GREAT PUMPKIN', 'SANTA'},
        bulletsNames = {'DAIKON', 'BROCCOLI', 'RADISH', 'CARROT', 'AVOCADO', 'STRAWBERRY', 'PEAR',
        'TAIYAKI', 'DORAYAKI', 'CHOCOLATE BAR', 'POPSICLE', 'LOLLIPOP', 'CARNATION', 'TRUMPET', 'TREBLE CLEF', 'RUBBER DUCK'},
        reset = 'RESET SCORES',
        resetConfirmTitle = 'ARE YOU SURE?',
        resetConfirmYes = 'YES, DELETE ALL SCORES',
        resetConfirmNo = 'NOPE, GO BACK',
        credits = 'CREDITS',
        creditsContent = "PROJECT BY GIULIA FANZAGHI\nLITERALLY MADE WITH LÖVE (THE 2D GAME FRAMEWORK)\nSKY BACKGROUND BY CANIA - ITCH.IO (EDITED BY ME)\nPIXEL ART FROM DOTOWN-MAEDA DESIGN ROOM (EDITED BY ME)\nSOUNDS EFFECTS GENERATED WITH BFXR OR FROM PIXABAY\nFONT IS APPLE II",
        creditsThanks = 'SPECIAL THANKS TO',
        creditsThanksContent = "COOPER AND MULDER, MY LOVELY CATS\nMATTEO, MY AWESOME HUSBAND"
    },

    {
        name = 'ITALIANO',
        newGame = 'NUOVA PARTITA',
        highScores = 'CLASSIFICA',
        options = 'OPZIONI',
        exit = 'ESCI',
        score = 'PUNTI',
        lives = 'VITE',
        paused = 'IN PAUSA',
        resume = 'RIPRENDI',
        abort = 'ABBANDONA MISSIONE',
        gameOver = 'GAME OVER',
        gameOverComment1 = 'WOW! NUOVO RECORD!',
        gameOverComment2 = 'WOW! SEI IN CLASSIFICA!',
        gameOverComment3 = 'AHI! QUESTI GATTI SONO TOSTI!',
        scoreIs = "IL TUO PUNTEGGIO E' ",
        playAgain = 'GIOCA ANCORA',
        menu = "MENU'",
        back = 'INDIETRO',
        language = 'LINGUA',
        sound = {
            [1] = 'SUONI: ATTIVI',
            [0] = 'SUONI: DISATTIVATI'
        },
        choosePlayer = 'SCEGLI IL TUO GUERRIERO',
        choosePlayerTitle = 'IL GUERRIERO',
        chooseBullet = 'SCEGLI LA TUA ARMA',
        chooseBulletTitle = 'LA TUA ARMA',
        select = 'SELEZIONA',
        playersNames = {'PROTAGONISTA', 'ELEGANTONE', 'CANOTTIERA', 'IN ROSA', 'IL POSTINO', 'RAPPER',
        'BASSOTUBA', 'NINJA', 'GREEN RANGER', 'CAVALLO ROSA', 'ZUCCA', 'BABBO NATALE'},
        bulletsNames = {'DAIKON', 'BROCCOLO', 'RAVANELLO', 'CAROTA', 'AVOCADO', 'FRAGOLA', 'PERA',
        'TAIYAKI', 'DORAYAKI', 'CIOCCOLATA', 'GHIACCIOLO', 'LECCA LECCA', 'GAROFANO', 'TROMBA', 'CHIAVE DI VIOLINO', 'PAPERETTA'},
        reset = 'CANCELLA LA CLASSIFICA',
        resetConfirmTitle = 'DAVVERO?',
        resetConfirmYes = "SI, ELIMINA I PUNTEGGI",
        resetConfirmNo = 'NO, TORNA INDIETRO',
        credits = 'CREDITS',
        creditsContent = "UN PROGETTO DI GIULIA FANZAGHI\nFATTO CON LÖVE (FRAMEWORK PER GIOCHI 2D)\nSFONDO DI CANIA - ITCH.IO (MODIFICATO DA ME)\nPIXEL ART DA DOTOWN-MAEDA DESIGN ROOM (MODIFICATA DA ME)\nEFFETTI SONORI GENERATI CON BFXR O DA PIXABAY\nIL FONT E' APPLE II",
        creditsThanks = 'RINGRAZIAMENTI SPECIALI',
        creditsThanksContent = "COOPER E MULDER, I MIEI ADORABILI GATTONI\nMATTEO, IL MIO FAVOLOSO MARITO"
    }

}